import pickle

TarotCards = {"The Fool (I)" : "The personality in the primal state, the willful child in all of us. Instinct. Innocence. Impulsive actions. Setting off in a new direction in life. Liberation of the impulses. Insight and wit from instinct rather than instruction.",
"The Magician (II)" : "Mastery of words and of matter. Eloquence, including eloquent silence and Hermetic wisdom. Mediator, messenger and communicator. The Magician may be a sage or just a quick talker. He is a master-manipulator of the material world, but the miracles he effects may be true physical and metaphysical transofmration or mere illusion and technical tricks. With Hermes one never knows, he is the god of orators and liars, merchants and thieves, trickery and arcane science.",
"The Priestess (III)" : "The abstract, spiritual and intellectual face of the anima, which is the feminine nature of the soul. Primordial feminine wisdom. The cyclic and balancing forces of nature. The ancient underground tradition of healing arts, magic and spiritual mystery.",
"The Empress (IV)" : "Feminine fertility and power. Civilization. Domestic tradition. Family and childrearing. The active, fecund aspect of the anima. The mother and the queen, on earth and in heaven.",
"The Emperor (V)" : "Worldly authority. Professional success. Social power. The life of action and decision, especially in politics and business. Patriarch, clan leader and pater familias.",
"The Hierophant (VI)" : "The abstact, spiritual and intellectual side of the animus, or masculine nature of the soul. Spiritual authority. Religious tradition. Avuncular wisdom. The old order and the old school.",
"Lovers (VII)" : "Romantic passion. Amorous attachment. The stages of love, discovery, attraction, pursuit, flirtation, courtship and consummation. The gifts of Aphrodite, beauty, youth, dalliance and delight.",
"Chariot (VIII)" : "Victory. Triumph over opposition. New order. Change by force. The chariot of the soul pulled to one side by the force of vigilance and restraint, or drawn to the other side by the force of the passions.",
"Justice (IX)" : "The vindication of the just and the punishment of the unjust. Rule of reason. Balance of power.",
"Hermit (X)" : "Introspection. Retreat. Pilgrimage. Spiritual quest. The search in oneself and in the world for the 'honest man' of Diogenes the philosopher. Meditation on the passage of time and the dissolution of matter.",
"Chance (XI)" : "The intrusion of chance into affairs. Unlikely coincidence. 'What goes up, must come down.' The intercession of good fortune in life. A sudden opportunity that must be exploited deftly and promptly; according to Machiavelli, in The Prince, Fortune is 'bald behind,' that is, once she runs past it will be too late to grab her, and so she must be seized as she approaches, 'by the forelock.'",
"Strength (XII)" : "Strength and fortitude. Moral resolve. Triumph over base instincts. Mens sana in corpore sana, 'Sound mind in a sound body.'",
"The Hanged Man (XIII)" : "Sacrifice. Vigilance. Martyrlike forbearance. Suspension or paralysis of the soul. A mind divided and undecided. Stasis and constraint.",
"Death (XIV)" : "Death. Loss. Death and rebirth. End of an old situation and the beginning of a new one.",
"Temperance (XV)" : "Balance. Moderation. Harmony. 'Nothing in excess.' Blending of opposites. Androgyny.",
"The Devil (XVI)" : "Wickedness and danger. Darkness and licentiousness. Slavery to the senses. Imprisonment by baser instincts. Temptation. Selfishness.",
"The Tower (XVII)" : "Comeuppance. Setback. Disaster. Arrogance or pride cast down by Providence. Unforeseen event. Calamity.",
"The Stars (XVIII)" : "Blessedness. Tranquility. Beauty.",
"The Moon (XIX)" : "Mystery. Changeability. Unseen and unknown forces of the night, and unpredictable transformations from the mutable moon. Young womanhood. Feminine beauty. Ordeal and honor of childbearing.",
"The Sun (XX)" : "Glory and rejoicing. The light of reason. The flower of manhood. Inspiration in poetry and music.",
"The Angel (XXI)" : "Resurrection and rebirth. Perfection of the body and soul. Final reward or punishment.",
"The World (XXII)" : "Completion and perfection. Focus. Synthesis. Interweaving. The vast design of nature. The interconnecting patterns of experience. Fulfillment and success.",
"Ace of Cups" : "The free reign of the heart in overflowing joy and abundant love.",
"Two of Cups" : "The flower of first love, of love at first sight. The bond between two people, invisible but formidable.",
"Three of Cups" : "Rescue from difficulty. Comfort after apprehension. A strange but beautiful occurrence.",
"Four of Cups" : "Jealousy and envy. Suspicion of a loved one. Nagging doubts.",
"Five of Cups" : "Serious, but not irreversible, mistake. A betrayal born of a lack of faith. Beauty lost and found, where ugliness was expected.",
"Six of Cups" : "Regret and nostalgia for a time past or a love lost. Disillusionment.",
"Seven of Cups" : "Living in a world of fantasy and illusion. Unrealistic and vain hopes. Dependence on external and even supernatural aid.",
"Eight of Cups" : "A moment of surrender to external forces. Capitulation to inner promptings. Giving in to temptation. Giving oneself over to oblivion, to intoxication, to sleep.",
"Nine of Cups" : "Difficulties overcome. Favorable agreement. Reconciliation. A new beginning. Renewal of trust. Bestowal of foregiveness.",
"Ten of Cups" : "The union of love and the soul. Happiness in love. Balance in friendship. Joyful equanimity in oneself.",
"Page of Cups" : "A young person or sensitive and meditative nature, capable of deep loyalty and profound affection. A conscientious worker.",
"Knight of Cups" : "A person of turbulent, poetic, romantic cast. An opportunity or favorable event in the near future. Deep feeling transformed into verse, music or visions.",
"Queen of Cups" : "A person of generous and loving nature, graceful and sparkling as a mountain stream, or deep and serene as a country lake. A poetess, musician or actress.",
"King of Cups" : "A dignified and accomplished person, compassionate and intuitively accurate. A successful professional, humanitarian and idealistic. One who appreciates the Dionysian side of the arts and the wild, mysterious aspect of nature.",
"Ace of Coins" : "Prosperity. Security. Wellbeing. Material riches and spiritual richness.",
"Two of Coins" : "Unusual turn of events. Unexpected difficulties. Untried emotions. Uncharacteristic behavior.",
"Three of Coins" : "Beauty. Balance. Harmony. Wellbeing.",
"Four of Coins" : "Lustful or greedy pursuit of someone or something. Irrational attraction. Unreasonable desire for wealth.",
"Five of Coins" : "Impoverishment and barrenness. Yearning for one absent.",
"Six of Coins" : "Generosity, Philanthropy. Charity. A wise and compassionate decision.",
"Seven of Coins" : "A step forward, accomplished with grace and skill.",
"Eight of Coins" : "Frankness, honesty and innocence. Candid confrontation of circumstances.",
"Nine of Coins" : "Balance. Compromise. Security. The cycle of nature. The protection of family. A season of dormancy which makes later fertility possible.",
"Ten of Coins" : "Prosperity. Tranquility. Family affection.",
"Page of Coins" : "An intelligent and sensible young person. Dependable and practical person who yet hides mysterious corners of himself and hoards secret treasures. An admirer of the patterns of the heavens, the makeup of nature, or the language of numbers.",
"Knight of Coins" : "A responsible and hardworking young person, efficient and persevering. An organizer, cataloguer and pathfinder. A person attached to the realities of life, but with a quixotic streak. A person who is serious, but quick to laugh.",
"Queen of Coins" : "A person who embodies richness and fertility, generous, opulent, gracious and noble. A cornucopia of delights. A rock of security. A brilliant crystal of insight. A rich field for new growth.",
"King of Coins" : "A master of the material world. A man of affairs who is successful, expert and pragmatic. One who extracts wealth from its hiding places. A builder. A pillar of family, clan and community.",
"Ace of Staves" : "Creativity. Change. Success in new undertakings. 'A breath of fresh air.' 'New blood.' The sanguine temperament of the ace promotes experiment, reform and appreciation of beauty, both of people and of nature.",
"Two of Staves" : "A decisive, perhaps early, accomplishment. Confirmation of boldness and courage.",
"Three of Staves" : "Achievement attained after a long chase. A rare and glowing prize.",
"Four of Staves" : "Calm, pleasurable and perhaps amorous interlude. A playful balance of opposites, like the exchange between Herakles and Queen Omphale.",
"Five of Staves" : "A project or adventure abandoned or cut short because of the departure or disappearance of a necessary colleague, partner, friend or lieutenant.",
"Six of Staves" : "Triumph over great difficulties. A glorious victory. 'If at first you don't succeed, try, try again.'",
"Seven of Staves" : "Splended award or valuable prize earned by one's wits, and by tricks and counter moves.",
"Eight of Staves" : "An explosion of movement and activity. A dramatic event. An unusual manifestation.",
"Nine of Staves" : "Attempted betrayal in the guise of aid. Hidden enemies, risk and conflict.",
"Ten of Staves" : "A final trial before an enduring reward. The greater the struggle, the greater the reward.",
"Page of Staves" : "A young person of faithful countenance who, even unintentionally, helps others. An unofficial Hermes: a carrier of important news, an envoy, a guide, a pleasant stranger. A suave, bright and noble soul.",
"Knight of Staves" : "A traveler. A journey. The call of faraway places. The arrival or return of a pilgrim or wanderer. A person of far-ranging interests and restless curiosity who is desirious of change and transformation. Inventive and artistic, but sometimes absent-minded person. Having one's 'head in the clouds.'",
"Queen of Staves" : "A person of sunny disposition, accomplished, graceful, and gracious. A patroness or adept of the fine arts and sciences. A wedding of intelligence and creativity, giving flower in fruitfulness.",
"King of Staves" : "A Renaissance man, practical and imaginative, active and contemplative, forceful and chivalrous. Appreciation of the lessons and pleasures of life. Worldliness in the best sense. An intellectual, an artist or an inventor.",
"Ace of Swords" : "In the realm of events, the card signifies triumphant power, whether for good or ill. For the life of the mind it represents the active, passionate impulses. It declares the dominance of the will and zealous, even fanatical, political or religious convictions. It is the sword of righteousness.",
"Two of Swords" : "Friendship, especially between student and teacher orr younger and older. The adventure and excitement of childhood and adolescence.",
"Three of Swords" : "Conflict of two mighty forces for the possession or mastery of something or someone. A dangerous triangle.",
"Four of Swords" : "Retreat from the battlefield of life. A rest from conflicts with colleagues or competitors. Calm in the storm. Self-imposed exile.",
"Five of Swords" : "Stubbornness. Refusal to move into the future, to forget the past or to face pressing responsibilities. Dishonor. Stagnation.",
"Six of Swords" : "A daring expedition. An excursion or trip. Courageous trip. Show of bravery.",
"Seven of Swords" : "Favorable turn of events. Hope for sustained success. Vigilance and strength.",
"Eight of Swords" : "Emotional disaster. Loss of a beloved person or a valued situation. A sadness that creates new strength and resolve.",
"Nine of Swords" : "Revenge. Excessive or violent response to a problem. Jealousy.",
"Ten of Swords" : "Calamity. The failure of a hero, foretold in prophecy, but brought about by the hero's own choices.",
"Page of Swords" : "A passionate young person given to seeking out the heart of the matter, even to the point of spying. Vigilance and quiet intensity.",
"Knight of Swords" : "An enthusiastic man of action. One who confronts the world at full speed, with head held high. Sunny but fierce and leonine person. An uncompromising judge of character, like Michael the archangel.",
"Queen of Swords" : "A person of sharp insight, persuasive, powerful and thorough. If extroverted, an administrator, an organizer, a firebrand, splendid as a summer's day - and sometimes as overwhelming. If introverted, a person of deep sentiment, susceptible to flights of ecstacy or the flames of inner torment.",
"King of Swords" : "A man of volatile temperament. A born fighter and ruler. A person in complete command. Self-mastery. Expertise. A person who prefers action to reflection - above all, dramatic, decisive action."
}


f = open("C:\\_PythonClass\\TarotCards.pkl", "wb")
pickle.dump(TarotCards, f)
f.close()
